#' Create an biodiversity profile of the retrieved data
#'
#' @description
#' This function creates a biodiversity profile of the downloaded data using [bold.fetch()].
#'
#' @param bold.df A data frame obtained from [bold.fetch()].
#' @param taxon.rank A single character value specifying the taxonomic hierarchical rank. Needs to be provided by default.
#' @param taxon.name A single or multiple character vector specifying the taxonomic names associated with the ‘taxon.rank’. Default value is NULL.
#' @param site.cat A single character vector specifying the geographic category for which a community matrix should be created. Default value is NULL.
#' @param grids.cat A logical value specifying Whether the community matrix should be based on grids as ‘sites’. Default value is NULL.
#' @param gridsize A numeric value of the size of the grid if the grids=TRUE; Size is in sq.m. Default value is NULL.
#' @param presence.absence A logical value specifying whether the generated matrix should be converted into a ’presence-absence’ matrix.
#' @param richness.res A logical value specifying whether richness results should be calculated. Default value is FALSE.
#' @param rich.plot.curve A logical value specifying whether an accumulation curve should be plotted. Default value is FALSE.
#' @param rich.curve.estimatr A character value specifying which index should be used. Default value is NULL.
#' @param rich.curve.x.axis A character value specifying whether 'samples' or 'individuals' should be used against the `rich.curve.estimatr`. Default value is NULL.
#' @param shannon.res A logical value specifying whether the Shannon diversity results should be gen- erated. Default value is FALSE.
#' @param preston.res A logical value specifying whether the Preston results should be generated. De- fault value is FALSE.
#' @param pres.plot.y.label A character value specifying the taxonomic category (`taxon.rank`) which was used to generate the matrix.
#' @param beta.res A logical value specifying whether beta diversity results should be calculated. Default value is FALSE.
#' @param beta.index A character vector specifying the type of beta diversity index (’jaccard’ or ’sorensen’ available).
#'
#' @details `bold.analyze.diversity` estimates the richness, Shannon diversity and beta diversity from the BIN counts or presence-absence data. Internally, the function converts the downloaded BCDM data into a community matrix (site X species) which is also generated as a part of the output. grids.cat converts the Coordinate Reference System (CRS) of the data to a ‘Mollweide’ projection by which distance-based grid can be correctly specified (Gott III et al. 2007).Each grid is assigned a cell id, with the lowest number given to the lowest latitudinal point in the dataset.
#' The community matrix generated by the function is used to create richness profiles using `BAT::alpha.accum()` and Preston and Shannon diversity analyses using `vegan::prestondistr()` and `vegan::diversity()` respectively. The `BAT::alpha.accum()` currently offers various richness estimators, including Observed diversity (Obs); Singletons (S1); Doubletons (S2); Uniques (Q1); Duplicates (Q2); Jackknife1 abundance (Jack1ab); Jackknife1 incidence (Jack1in); Jackknife2 abundance (Jack2ab); Jackknife2 incidence (Jack2in); Chao1 and Chao2. The results depend on the input data (true abundances vs counts vs incidences) and users should be careful in the subsequent interpretation.
#' Preston plots are generated using the data from the `prestondistr` results in `ggplot2` featuring cyan bars for observed species (or equivalent taxonomic group) and orange dots for expected counts. The `presence.absence` argument converts the counts (or abundances) to 1s and 0s. This dataset can then be directly used as input data for biodiversity analysis functions from packages like vegan.
#' Beta diversity values are calculated using `BAT::beta()` function, which partitions the data using the Podani & Schmera (2011)/Carvalho et al. (2012) approach partitioning the beta diversity into ’species replacement’ and ’richness difference’ components. These results are stored as distance matrices in the output.
#' \emph{Note on the community matrix}: Each cell in this matrix contains the counts (or abundances) of the specimens which sequence have an assigned BIN, in a given a site category (`site.cat`) or a grid  (`grids.cat`). These counts can be generated at any taxonomic hierarchical level, applicable to one or multiple taxa including ’bin_uri’. The `site.cat` can refer to any geographic field, and metadata on these fields can be checked using the `bold.fields.info()`. If, `grids.cat` = TRUE, grids are generated based on BIN occurrence data (latitude, longitude) with grid size determined by the user in square meters using the `gridsize` argument. Rows lacking latitude and longitude data are removed, while NULL entries for site.cat are allowed if they have a latitude and longitude value. This is because grids are drawn based on the bounding boxes which only use latitude and longitude values
#' \emph{Important Note}: Results, including species counts, adapt based on taxon.rank argument although the output label remains ‘species’ in some instances (`preston.res`).
#'
#' @returns An 'output' list containing containing:
#' *	comm.matrix = site X species like matrix required for the biodiversity results
#' *	richness = A richness profile matrix
#' *	Shannon_div = Shannon diversity values for the given sites/grids (from gen.comm.mat)
#' *	richness_plot = A ggplot2 visualization of the richness curve
#' *	preston.res = a Preston plot numerical data output
#' *	preston.plot = a ggplot2 visualization of the preston.plot
#' *	total.beta = beta.total
#' *	replace = beta.replace (replacement)
#' *	richnessd = beta.richnessd (richness difference)
#'
#' @references
#' Carvalho, J.C., Cardoso, P. & Gomes, P. (2012) Determining the relative roles of species replace- ment and species richness differences in generating beta-diversity patterns. Global Ecology and Biogeography, 21, 760-771.
#'
#' Podani, J. & Schmera, D. (2011) A new conceptual and methodological framework for exploring and explaining pattern in presence-absence data. Oikos, 120, 1625-1638.
#'
#' Richard Gott III, J., Mugnolo, C., & Colley, W. N. (2007). Map projections minimizing distance errors. Cartographica: The International Journal for Geographic Information and Geovisualization, 42(3), 219-234.
#'
#' @examples
#' \dontrun{
#'
#' # Search for ids
#' comm.mat.data <- bold.public.search(taxonomy = "Poecilia")
#'
#' # Fetch the data using the ids
#' # api_key must be obtained from BOLD support before usage.
#' BCDMdata <- bold.fetch(param.data = comm.mat.data,
#' query.param = "processid",
#' param.index = 1,
#' api_key = apikey)
#'
#' # Remove rows which have no species data BCDMdata <- BCDMdata[!BCDMdata$species == "",]
#'
#' #1. Analyze richness data
#' res.rich <- bold.analyze.diversity(BCDMdata,
#' taxon.rank = "species",
#' site.cat = 'country.ocean',
#' richness.res = TRUE)
#'
#' # Community matrix (BCDM data converted to community matrix) res.rich$comm.matrix
#'
#' # richness results res.rich$comm.matrix
#'
#' #2. Shannon diversity
#' res.shannon <- bold.analyze.diversity(BCDMdata,
#' taxon.rank = "species",
#' site.cat = 'country.ocean',
#' shannon.res = TRUE)
#'
#' # Shannon diversity results res.shannon
#'
#' #3. Preston plots and results
#' pres.res < -bold.analyze.diversity(BCDMdata,
#' taxon.rank = "species",
#' site.cat = 'country.ocean',
#' preston.res = TRUE)
#'
#' # Preston plot pres.res$preston.plot
#'
#' # Preston plot data pres.res$preston.res
#'
#' #4. beta diversity
#' beta.res <- bold.analyze.diversity(BCDMdata,
#' taxon.rank = "species",
#' site.cat = 'country.ocean',
#' beta.res = TRUE,
#' beta.index = "jaccard")
#'
#' #Total diversity
#' beta.res$total.beta
#'
#' #Replacement
#' beta.res$replace
#'
#' #Richness difference
#' beta.res$richnessd
#'
#'}
#'
#' @importFrom BAT alpha.accum
#' @importFrom vegan diversity
#' @importFrom vegan prestondistr
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 theme_classic
#' @importFrom ggplot2 sym
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 element_blank
#' @importFrom stats fitted
#' @importFrom BAT beta
#' @export
#'
bold.analyze.diversity <- function(bold.df,
                                   taxon.rank,
                                   taxon.name=NULL,
                                   site.cat=NULL,
                                   grids.cat=FALSE,
                                   gridsize=NULL,
                                   presence.absence=FALSE,
                                   richness.res=FALSE,
                                   rich.plot.curve=FALSE,
                                   rich.curve.estimatr=NULL,
                                   rich.curve.x.axis=NULL,
                                   shannon.res=FALSE,
                                   preston.res=FALSE,
                                   pres.plot.y.label=NULL,
                                   beta.res=FALSE,
                                   beta.index=NULL)

{

  # Check if data is a data frame object

  if(is.data.frame(bold.df)==FALSE)

  {

    stop("Input is not a data frame")

    return(FALSE)

  }


  # Check whether the data frame is empty

  if(nrow(bold.df)==0)

  {

    stop("Dataframe is empty")

    return(FALSE)

  }

  # Empty output list

  output = list()

  # Condition to check if grids.cat is specified or whether site.cat will be used

  if(grids.cat)

  {

    if(is.null(gridsize))

    {

      stop("When grids.cat=TRUE, gridsize must be specified")

    }

    else

      {

      bin.comm.res = gen.comm.mat(bold.df=bold.df,
                                taxon.rank=taxon.rank,
                                taxon.name=taxon.name,
                                site.cat=site.cat,
                                grids=grids.cat,
                                gridsize=gridsize,
                                view.grids=TRUE)

    bin.comm = bin.comm.res$comm.matrix

    grids.map=bin.comm.res$grid_plot

    output$grid.map=grids.map

    }

    # else if (grids.cat==F)
    #
    # {
    #
    #   if(!is.null(gridsize))
    #
    #   {
    #
    #     stop("gridsize specified when grids.cat=FALSE. Please re-check the inputs.")
    #
    #   }
    #
    #
    # }

  }

  else

  {

   if (!is.null(site.cat))

     {

     bin.comm.res = gen.comm.mat(bold.df=bold.df,
                                taxon.rank=taxon.rank,
                                taxon.name=taxon.name,
                                site.cat=site.cat)

    bin.comm = bin.comm.res$comm.matrix

   }

    else if (any(!is.null(site.cat) && grids.cat==F|!is.null(gridsize)))

    {

      stop("grid.cat or gridsize specified when site.cat is specified. Please re-check the inputs.")

    }


  }


  # Check if the data is presence-absence

  if(presence.absence)

  {

    bin.comm=ifelse(bin.comm>=1,1,0)%>%data.frame(.)

  }


  # Output the community data

 output$comm.matrix = bin.comm

 # Richness results

  if(richness.res)

  {

    # species richness estimation

    richness=alpha.accum(bin.comm,
                         runs=100)%>%
      data.frame(.)%>%
      dplyr::mutate(across(where(is.numeric), ~ round(., 2)))


    output$richness = richness

    # Richness curves

    if(rich.plot.curve)

    {
      if(is.null(rich.curve.estimatr)|is.null(rich.curve.x.axis))

      {

        stop("If rich.plot.curve=TRUE, rich.curve.estimatr and rich.curve.x.axis must be specified")

      }

      else

      {
        # Estimation curves in ggplot2

        x_data = ggplot2::sym(rich.curve.x.axis)


        y_data = ggplot2::sym(rich.curve.estimatr)


        richness = richness

        colnames(richness)[colnames(richness) == 'Ind'] <- 'Individuals'

        colnames(richness)[colnames(richness) == 'Sampl'] <- 'Samples'

        richness_plot=richness%>%
          dplyr::select(!!x_data,
                        !!y_data)%>%
          ggplot(aes(x=!!x_data,
                     y=!!y_data)) +
          geom_line(linewidth=1.5)+
          theme_classic(base_size = 16) +
          theme(panel.grid.major = element_blank(),
                panel.grid.minor = element_blank())


        output$richness_plot = richness_plot

      }

    }

    else if (richness.res==FALSE && any((rich.plot.curve==TRUE)|!is.null(rich.curve.estimatr)|!is.null(rich.curve.x.axis)))

      stop("richness.res should be TRUE for plotting richness curves")

  }

 # Shannon diversity

  if (shannon.res)

  {

    if (all(bin.comm==0|bin.comm==1))

    {
      warning("Data is presence absence data. Shannon values calculated here are based on the assumption that the BIN community data have counts (or abundances)")
    }

    # Shannon diversity


    shannon_div=vegan::diversity(bin.comm)%>%
      data.frame(.)%>%
      dplyr::rename("Shannon_values"=".")

    output$Shannon_div = round(shannon_div,2)

  }

  # Preston plots


  if(preston.res)

  {

    if (all(bin.comm==0|bin.comm==1))

    {
      warning("Data is presence absence data. Preston results calculated here are based on the assumption that the BIN community data have counts (or abundances)")
    }


    tryCatch({

      preston.res = vegan::prestondistr(colSums(bin.comm))

      pres_res=data.frame(observed=as.matrix(preston.res$freq),
                          fitted=round(preston.res$fitted,2))

      pres_res$rownum = rownames(pres_res)

      pres_res=pres_res%>%
        dplyr::mutate(rownum=as.numeric(rownum))%>%
        dplyr::mutate(Octaves=as.factor(2^rownum))


      preston.plot=pres_res%>%
        ggplot(aes(x=Octaves,
                   y=observed))+
        geom_bar(stat = "identity",
                 position = 'dodge',
                 fill="darkcyan",
                 col="black",
                 width = 1) +
        geom_point(data = pres_res,
                   aes(x = Octaves,
                       y = fitted,
                       group=1),
                   pch=21,
                   color = "black",
                   fill="orangered",
                   size=4) +
        geom_line(data = pres_res,
                  aes(x = Octaves,
                      y = fitted,group=1),
                  color = "black",
                  lty=2,
                  linewidth=1) +
        theme_bw(base_size = 16) +
        theme(panel.grid.major = element_blank(),
              panel.grid.minor = element_blank())+
        ylab("Species")+
        xlab("Frequency") +
        scale_y_continuous(expand = c(0,0)) +
        ylab(pres.plot.y.label)+
        ggtitle("Preston plot")


      output$preston.plot = preston.plot

      output$preston.res = preston.res


    },

    error = function (e)

    {

      message("The following error is for the preston results due to an issue with the input data. Please re-check if the values used are abundances or presence-absences: ",e$message)



    }
    )



  }

 # Beta diversity


  if(beta.res)

  {


    beta.bin.div=BAT::beta(bin.comm,
                      func = beta.index,
                      abund = presence.absence,
                      runs=10,
                      comp = T)



    beta.total = beta.bin.div$Btotal

    beta.replace = beta.bin.div$Brepl

    beta.richnessd = beta.bin.div$Brich

    # Add results to output

    output$total.beta = beta.total


    output$replace = beta.replace


    output$richnessd = beta.richnessd


  }


  invisible(output)


}
