#'Generate a summary of the data downloaded from BOLD
#'
#' @description
#' The function is used to obtain a detailed summary of the data obtained by `bold.fetch` function.
#'
#' @param bold_df the data.frame retrieved from the `bold.fetch` function.
#' @param summarize_by A single character value specifying the type of summary required ("fields","presets","all_data" currently available)
#' @param columns A single or multiple character vector specifying the columns for which a data summary is sought. Default value is NULL.
#' @param presets A single character vector specifying a preset for which a data summary is sought (Check the `details` section for more information). Default value is NULL.
#' @param na.rm A logical value specifying whether NA values should be removed from the BCDM dataframe. Default value is FALSE.
#'
#' @details
#' `bold.data.summarize` provides summaries for each data type available in the downloaded dataset. The function uses the `skimr::skim()` function to generate a list of data frames which are then separated by data type using `skimr::partition()` to facilitate streamlined export. `na.rm`= TRUE removes all NA values. Summaries can be generated by one of three ways, a) using `all_data` that considers all data, b) using specific `presets`that are defined set of columns representing a specific aspect of the BOLD BCDM data (currently available are: `taxonomy`,`geography`,`sequences`,`attributions`, `ecology_biogeography` and `other_meta_data`) and c) `fields` which lets the user select any specific columns. `presets` names can be directly typed without quotations. The summary includes counts for NULL values, unique values and the proportion of complete cases. Both `presets` and `fields` by default, are set to NULL. Summaries are printed to the console and can also be saved. Please note that if the `cols` argument from [bold.fetch()] has been used to filter for specific columns,  and only those will be summarized by default if `all_data` option is selected. For specific details on the skim output, refers to the `skimr` package documentation.
#'
#' @returns A list of data frames. Each data frame is a data summary of a specific data type.
#'
#' @examples
#' \dontrun{
# Download data
#' bold_data.ids <- bold.public.search(taxonomy = "Oreochromis")
#'
#' # Fetch the data using the ids.
#' #1. api_key must be obtained from BOLD support before usage
#' #2. the function `bold.apikey` should be used to set the apikey in the global env
#'
#' bold.data <- bold.fetch(get_by = "processid",
#'                         identifiers = bold_data.ids$processid)
#'
#' #1. Generate summary for the whole data
#'
#' test.data.summary <- bold.data.summarize(bold_df=bold.data,
#'                                          summarize_by = "all_data")
#'
#' # All summary
#' test.data.summary
#'
#' #2. Generate summary for specific fields (cols)
#' test.data.summary.cols <- bold.data.summarize(bold_df=bold.data,
#'                                               summarize_by = "fields",
#'                                               columns = c("country.ocean",
#'                                                           "nuc_basecount",
#'                                                           "inst",
#'                                                           "elev"),
#'                                              na.rm = F)
#'
#' # Character data fields summary
#' test.data.summary.cols$character
#'
#' # Numerical data fields summary
#' test.data.summary.cols$numeric
#'
#' #3. Preset based summary
#' test.data.summary.preset <- bold.data.summarize(bold_df=bold.data,
#'                                                 summarize_by = "presets",
#'                                                 presets = 'geography',
#'                                                 na.rm = F)
#'
#' # All summary with respect to geography related fields in the BCDM data
#' test.data.summary.preset
#'}
#'
#' @importFrom skimr skim
#' @importFrom skimr partition
#' @importFrom skimr skim_with
#' @import dplyr
#'
#' @export
#'
bold.data.summarize<-function(bold_df,
                            summarize_by = c("fields","presets","all_data"),
                            columns = NULL,
                            presets = NULL,
                            na.rm=FALSE) {

  # Check for data structure

  # Check if data is a data frame object

  if (!is.data.frame(bold_df)) {
    stop("Input data should be a BCDM dataframe")
  }


  # Check whether the data frame is empty

  if (nrow(bold_df)==0) {
    stop("Input data should be a BCDM dataframe")
  }


  if(na.rm)
  {
    bold_df=bold_df%>%
      tidyr::drop_na(.)
  }


  total_rows_cols<-function (df)

  {

    Rows=nrow(df)

    Columns=ncol(df)

    message<-paste("The total number of rows in the dataset is:",Rows,"\nThe total number of columns in the dataset is:",Columns)

    cat(message)

  }


  suppressMessages(skim_with(numeric=list(digits=2)))

  switch (summarize_by,

          "fields" =

            {

              if (is.null(columns)) {
                stop("Columns should not be NULL when summarize_by=fields")
              }


            # Verification of column names

            if (any(!columns %in% colnames(bold_df)))

              {
              stop("Column names given are not present in the input BCDM dataframe")
                }

              # generate the summary

              total_rows_cols(bold_df)

              summary.bold.df=suppressWarnings(bold_df%>%
                                                 dplyr::select(all_of(columns))%>%
                                                 skimr::skim(.)%>%
                                                 mutate(across(where(is.numeric), ~ round(., 2)))%>%
                                                 skimr::partition(.))
              },

          "presets" =

            {
              if (is.null(presets))

              {
                stop("Presets should not be NULL when summarize_by=presets")
              }



              data_for_summary = check_and_return_preset_df(df=bold_df,
                                                            category = "check_return",
                                                            preset = presets)

              #total_rows_cols(data_for_summary)

              summary.bold.df=suppressWarnings(data_for_summary%>%
                                                 skimr::skim(.)%>%
                                                 mutate(across(where(is.numeric), ~ round(., 2)))%>%
                                                 skimr::partition(.))
              },

          "all_data" =

            {
              if (any(!is.null(columns),!is.null(presets)))

              {
                stop("columns and presets should be NULL when summarize_by=all_data")
              }

              total_rows_cols(bold_df)

              summary.bold.df=suppressWarnings(bold_df%>%
                                                 skimr::skim(.)%>%
                                                 mutate(across(where(is.numeric), ~ round(., 2)))%>%
                                                 skimr::partition(.))

              }
          )


# Summary

return(summary.bold.df)

}
